-- reiniciar conteo para crear los roles y permisos
TRUNCATE TABLE public.auth_assignment RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.auth_item RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.auth_item_child RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.auth_rule RESTART IDENTITY CASCADE;
TRUNCATE TABLE comedor.usuario RESTART IDENTITY CASCADE;
TRUNCATE TABLE comedor.personal RESTART IDENTITY CASCADE;
TRUNCATE TABLE comedor.departamento RESTART IDENTITY CASCADE;
TRUNCATE TABLE comedor.perscomedor RESTART IDENTITY CASCADE;